### PR TITLE
fix: Upgrade next, react, typescript and eds

### LINKED ISSUE #567: Upgrade Next.js, EDS, React and TypeScript packages
We're currently running Next.js version 12, which should be upgraded to version 13.

Here is a guide: [Upgrading from 12 to 13](https://nextjs.org/docs/pages/building-your-application/upgrading/version-13)

### PR DESCRIPTION
**Pull request by nesadrian**
- Upgrade next from 12.3.4 to 14.0.4
- Upgrade react from 17.0.2 to 18.0.2
- Upgrade typescript from 4.5.5 to 5.3.3
- Upgrade eds from 0.17.0 to 0.35.1

Closes #567

### CODE REVIEW

File: components/FilterUserBox.tsx [hunk 1]
```diff
@@ -53,6 +53,7 @@ function SearchSection(props: {
         id="searchProjects"
         placeholder="Search users"
         autoComplete="off"
+        style={{ width: "100%" }}
```
Comment (dansvend) [inline components/FilterUserBox.tsx:56]: Please move styles into CSS module.

File: components/SearchField.tsx [hunk 2]
```diff
@@ -17,6 +17,7 @@ export function SearchField(): JSX.Element {
       aria-label="Search for process with name"
       placeholder="Search by process name"
       defaultValue={router.query.q}
+      style={{ width: "100%" }}
```
Comment (dansvend) [inline components/SearchField.tsx:20]: Please move styles into CSS module.

File: components/URLPrompt.tsx [hunk 3]
```diff
@@ -14,7 +14,7 @@ import { SelectionInfo } from "interfaces/SelectionInfo";
 import { transformLink } from "utils/transformLink";
 
 const getInputVariant = (url: string) => {
-  if (url.length === 0) return "default";
+  if (url.length === 0) return null;
```
Comment (dansvend) [inline components/URLPrompt.tsx:17]: Let's stick to `if (url.length === 0) return undefined;` as this is the value of an optional prop when not passing a value.

File: components/TooltipImproved.tsx [hunk 4]
```diff
@@ -1,20 +1,28 @@
...
+    <Tooltip title={props.title}>{props.children}</Tooltip>
+  );
 }
+
+export const TooltipImproved = dynamic(
+  () => Promise.resolve(TooltipComponent),
+  {
+    ssr: false,
+  }
+);
```
Comment (dansvend) [inline components/TooltipImproved.tsx:28]: The changes made to this file can be reverted if you add "use client" at the top of the file.

**Review by dansvend — CHANGES_REQUESTED** [review]
Nice with getting on top of version numbers of these packages 🧘

When installing dependencies I get warnings about incorrect version of peer dependencies. See comments for more details.

File: CHANGELOG.md [hunk 5]
```diff
@@ -2,261 +2,255 @@
 
 ## [0.2.35](https://github.com/equinor/flyt/compare/v0.2.34...v0.2.35) (2024-01-08)
 
-
```
[the remark this answers is not in the document]
Comment (nesadrian) [reply CHANGELOG.md:5]: It's because I merged the main branch into this branch

File: pages/process/[id]/download.tsx [hunk 6]
```diff
@@ -53,7 +53,9 @@ export default function Project() {
         </Head>
 
         <main className={commonStyles.main}>
-          <Typography variant="h1">{error.message}</Typography>
+          {typeof error?.message === "string" && (
```
[the remark this answers is not in the document]
Comment (nesadrian) [reply pages/process/[id]/download.tsx:56]: Yes, type unknown is not a valid Typography child type

File: package.json [hunk 7]
```diff
@@ -37,27 +37,27 @@
...
     "node-fetch": "2.6.12",
     "pixi-viewport": "4.38.0",
     "pixi.js": "6.2.2",
-    "react": "17.0.2",
+    "react": "^18.2.0",
     "react-device-detect": "2.2.3",
-    "react-dom": "17.0.2",
+    "react-dom": "^18.2.0",
     "react-is": "17.0.2",
     "react-json-view": "1.21.3",
```
[the remark this answers is not in the document]
Comment (nesadrian) [reply package.json:62]: I think this is not in scope for this issue

File: package.json [hunk 8]
```diff
@@ -91,7 +91,7 @@
     "prettier": "2.8.8",
     "pretty-quick": "3.1.3",
     "standard-version": "9.5.0",
-    "typescript": "4.5.5"
+    "typescript": "5.3.3"
   },
   "resolutions": {
     "simple-get": "4.0.1"
```
[the remark this answers is not in the document]
Comment (nesadrian) [reply package.json:97]: I think this is not in scope for this issue

**Review by dansvend — CHANGES_REQUESTED** [review]

File: package.json [hunk 9]
```diff
@@ -37,28 +37,28 @@
...
     "next-remove-imports": "1.0.11",
     "node-fetch": "2.6.12",
     "pixi-viewport": "4.38.0",
     "pixi.js": "6.2.2",
-    "react": "17.0.2",
+    "react": "^18.2.0",
     "react-device-detect": "2.2.3",
-    "react-dom": "17.0.2",
-    "react-is": "17.0.2",
+    "react-dom": "^18.2.0",
```
[the remark this answers is not in the document]
Comment (nesadrian) [reply package.json:60]: I checked both packages and they are currently on their latest version

File: components/AppHeader/UserMenu.tsx [hunk 10]
```diff
@@ -15,13 +16,11 @@ const UserMenu: React.FC = () => {
 
   const [state, setState] = React.useState<{
```
Comment (dansvend) [inline components/AppHeader/UserMenu.tsx:17]: Since the state is no longer an object, the name of this should have an updated name.

File: components/AppHeader/UserMenu.tsx [hunk 11]
```diff
@@ -15,13 +16,11 @@ const UserMenu: React.FC = () => {
...
     buttonEl: HTMLButtonElement;
-    focus: "first" | "last";
   }>({
-    focus: "first",
     buttonEl: null,
   });
 
-  const { focus, buttonEl } = state;
+  const { buttonEl } = state;
```
Comment (dansvend) [inline components/AppHeader/UserMenu.tsx:23]: This can be removed if you rename `state` to `buttonElement`.

File: components/DurationComponent.tsx [hunk 12]
```diff
@@ -38,15 +38,15 @@ export function DurationComponent(props: {
...
+        options={getTimeDefinitionValues()}
+        onInputChange={(i) => {
+          const apiValue = getTimeDefinitionValue(i);
           setUnit(apiValue);
           props.onChangeTime({ time: time, unit: apiValue });
         }}
-        value={getTimeDefinitionDisplayName(unit)}
+        selectedOptions={[getTimeDefinitionDisplayName(unit)]}
         label="Unit"
       />
```
Comment (dansvend) [inline components/DurationComponent.tsx:51]: This has some TypeScript errors when setting `strict: true` in `tsconfig.json`.

File: components/SelectTaskType.tsx [hunk 13]
```diff
@@ -18,15 +18,15 @@ export function SelectTaskType(props: { onSelect: (e) => void }): JSX.Element {
...
+        options={taskTypes.map((t) => t.name)}
+        onInputChange={(e) =>
           props.onSelect(
-            taskTypes.find((t) => e.selectedItem === t.name).vsmTaskTypeID //Wow... there must be a better way
+            taskTypes.find((t) => e === t.name).vsmTaskTypeID //Wow... there must be a better way
           )
         }
-        initialSelectedItem={taskTypes[0]?.name}
+        initialSelectedOptions={[taskTypes[0]?.name]}
       />
```
Comment (dansvend) [inline components/SelectTaskType.tsx:30]: This causes TypeScript errors when `strict: true` in `tsconfig.json`.

File: types/timeDefinitions.tsx [hunk 14]
```diff
@@ -10,8 +10,12 @@ export const timeDefinitions = [
 export const getTimeDefinitionValues = (): Array<string> =>
   timeDefinitions.map((item) => item.displayName);
 
-export const getTimeDefinitionValue = (displayName: string): string =>
-  timeDefinitions.find((item) => item.displayName === displayName).value;
+export const getTimeDefinitionValue = (displayName: string): string | null => {
+  const timeDefinitionValue = timeDefinitions.find(
+    (item) => item?.displayName === displayName
```
Comment (dansvend) [inline types/timeDefinitions.tsx:15]: No need for an optional chaining operator here.

File: types/timeDefinitions.tsx [hunk 15]
```diff
@@ -10,8 +10,12 @@ export const timeDefinitions = [
 export const getTimeDefinitionValues = (): Array<string> =>
   timeDefinitions.map((item) => item.displayName);
 
-export const getTimeDefinitionValue = (displayName: string): string =>
-  timeDefinitions.find((item) => item.displayName === displayName).value;
+export const getTimeDefinitionValue = (displayName: string): string | null => {
```
Comment (dansvend) [inline types/timeDefinitions.tsx:13]: Please remove the `|| null` as the places this function is used it expects `string | undefined`.

**Review by dansvend — CHANGES_REQUESTED** [review]

File: components/SelectTaskType.tsx (hunk 13 above)
Comment (nesadrian) [reply components/SelectTaskType.tsx:30]: This file is not being used and is deleted in Flyt 2.0. I'm deleting it here as well

File: types/timeDefinitions.tsx (hunk 15 above)
Comment (nesadrian) [reply types/timeDefinitions.tsx:13]: Type null is what we get from the server, so VsmObject.tsx should have had this typing already. I will add it. Passing null for this changed input field is good to indicate to the backend that changes has been made by the user.

File: components/DurationComponent.tsx (hunk 12 above)
Comment (nesadrian) [reply components/DurationComponent.tsx:51]: These errors was always an issue from the typing of the callback prop, and this callback is passed down multiple files. This should be fixed in #668

**Review by dansvend — APPROVED** [review]
Let's ship it 🚀 Good job 💪
